<a href="https://colab.research.google.com/github/JeremyElliot2077/Taller/blob/main/Apuntes_Numpy_C_AA2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# listas
pesos = [1.2, 1.4, 1.6]
alturas = [2.1, 1.5, 1.1]

# convertir a arreglos

# calcular imc

In [ ]:
table = [
    [15, 8, 3, 16, 12, 7, 9, 5],
    [6, 11, 9, 4, 1, 5, 8, 13],
    [17, 3, 5, 18, 10, 6, 7, 21],
    [8, 14, 13, 6, 13, 12, 8, 8],
    [1, 9, 5, 16, 20, 2, 3, 9]
]

In [ ]:
table

In [ ]:
# conversión de lista de listas en una matriz numpy
np_table = np.array(table)

In [ ]:
np_table

In [ ]:
type(table)

In [ ]:
type(np_table)

# Retos

## 1.- Tu primer array NumPy
En este capítulo, vamos a adentrarnos en el mundo del béisbol. En el camino, te sentirás cómodo con los aspectos básicos de Numpy, un poderoso paquete de Python para la ciencia de datos.

Una lista baseball ha sido definida en el guión de Python, la cual representa la altura en centímetros de algunos jugadores de béisbol. ¿Puedes agregar algunas líneas de código para crear un array numpy de dicha lista?

### Instrucciones

- Importa el paquete numpy como np, asi podrás referirte a numpy como np.
- Usa np.array() para crear un array numpy de la lista baseball. Llama a este array np_baseball.
- Imprime el tipo de dato de np_baseball para verificar que lo hiciste correctamente.


In [ ]:
# Importa el paquete Numpy como np
import numpy as np

# Crea la lista baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Crea el array Numpy de baseball: np_baseball


# Imprime el tipo de np_baseball




<class 'numpy.ndarray'>
[180 215 210 210 188 176 209 200]


## 2.- Altura de los jugadores de béisbol
Eres un gran fan del béisbol y decidiste llamar a la MLB (Grandes Ligas de Béisbol) para preguntar sobre algunas estadisticas referentes a la altura de los jugadores principales. Ellos te pasan información sobre más de mil jugadores, los cuales están almacenados como una lista de Python: height. La altura está expresada en pulgadas. ¿Puedes crear un array numpy de la lista y convertir las unidades a metros?

Tanto height como el paquete numpy se encuentran disponibles en el código, por lo que puedes empezar enseguida (Fuente: stat.ucla.edu).

## Instrucciones

- Crea un array numpy de height. Llama a este array np_height.
- Imprime np_height.
- Multiplica np_height con 0.0254 para convertir todas las medidas de altura de pulgadas a metros. Guarda estos valores en un nuevo array llamado np_height_m.
- Imprime np_height_m y revisa si el resultado tiene sentido.


In [ ]:
# Ejecutar este bloque para que funcione ejemplos posteriores
from data import *

In [ ]:
print(height)

[74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73,

In [ ]:
# height esta disponible como una lista

# Importa el paquete numpy
import numpy as np

# Crea un array numpy de height: np_height


# Imprime np_height


# Convierte np_height a m: np_height_m

# Imprime np_height_m

# Imprimir el primer elemento de np_height_m


[74 74 72 ... 75 75 73]
[1.8796 1.8796 1.8288 ... 1.905  1.905  1.8542]
1.8796


## 3.- IMC de los jugadores de béisbol
La MLB también ofrece los datos de pesos de sus jugadores. De nuevo, ambos están disponibles como listas de Python: height y weight. height está en pulgadas y weight en libras.

Ahora es posible calcular el IMC (Índice de masa corporal o BMI en inglés) para cada jugador de béisbol. El código en Python para convertir height a un array numpycon las unidades correctas ya se encuentra disponible en el espacio de trabajo. ¡Sigue las instrucciones paso a paso para termina el juego!

- Crea un array numpy de la lista weight con las unidades correctas. Multiplica por 0.453592 para convertir de libras a kilogramos. Guarda el resultado del array numpy como np_weight_kg.
- Utiliza np_height_m y np_weight_kg para calcular el IMC de cada jugador. Usa la siguiente ecuación:

$$BMI=\frac{weight(kg)}{height(m)^{2}}$$

In [ ]:
# height y weight están disponibles como listas

# Importa el paquete numpy
import numpy as np

# Crea un array de height con las unidades correctas: np_height_m
np_height_m = np.array(height) * 0.0254

# Crea un array de weight con las unidades correctas: np_weight_kg


# Calcula el IMC: bmi



# Imprime bmi




[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


##  4.- Jugadores de béisbol livianos
Para seleccionar tanto en una lista como en un array numpy en Python, puedes utilizar los corchetes:

    x = [4 , 9 , 6, 3, 1]
    x[1]
    import numpy as np
    y = np.array(x)
    y[1]
    
Especificamente para numpy, puedes utilizar también arrays numpy booleanos:
    
    high = y > 5
    y[high]
    
El código que calcula el IMC de todos los jugadores de béisbol ya está incluido. ¡Sigue las instrucciones y descubre cosas interesantes de esos datos!

### Instrucciones

- Crea un array numpy booleano: el elemento del array debería ser igual a Truesi el IMC del jugador correspondiente es menor a 21.Puedes utilizar el operador < para esto. Nombra el array como light.
- Imprime el array light.
- Imprime el array numpy que contiene todos los IMC de los jugadores de béisbol cuyo IMC es menor a 21. Utiliza light dentro de los corchetes para hacer una selección en el array bmi.

In [ ]:
# height y weight están disponibles como listas

# Importa el paquete numpy
import numpy as np

# Calcula el IMC: bmi
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Creaa el array light


# Imprime light



# Imprime el IMC de todos los jugadores de béisbol cuyo IMC es menor a 21



[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


## 6.- Selección en arreglos NumPy
Lo has visto con tus propios ojos: las listas y los arrays numpy a veces se comportan de manera diferente. Afortunadamente, aún existen certezas en este mundo. Por ejemplo, seleccionar (utilizando los corchetes en listas o arrays) funciona exactamente igual. Para que lo veas por ti mismo, prueba las siguientes líneas de código en la consola de Python:
    
    x = ["a", "b", "c"]
    x[1]

    np_x = np.array(x)
    np_x[1]

El guión a la derecha ya contiene el código que importa el paquete numpy como np, y guarda tanto la altura como el peso de los jugadores de béisbol como arrays numpy.

### Instrucciones
- Selecciona de np_weight: imprime el elemento en el índice 50.
- Imprime un sub-array de np_height: este contiene los elementos en el índice 100 hasta el índice 110 incluido.

In [ ]:
# height y weight están disponibles como listas

# Importa el paquete numpy
import numpy as np

# Guarda las listas weight y height como arrays numpy
np_weight = np.array(weight)
np_height = np.array(height)

# Imprime el peso del índice 50


# Imprime un sub-array de np_height: desde el índice 100 hasta el 110 incluido.


200
[73 74 72 73 69 72 73 75 75 73 72]
75
74


## 7.- Tu primer array 2D con NumPy

Antes de trabajar con los datos de las Grandes Ligas de Béisbol, vamos a intentar crear un array 2D numpy de una pequeña lista de listas.

En este ejercicio, baseball es una lista de listas. La lista principal contiene cuatro elementos. Cada uno de estos elementos es una lista que contiene la altura y el peso de cuatro jugadores de béisbol, en ese orden. baseball ya se encuentra definida para ti en el guión.

### Instrucciones

- Usa np.array() para crear un array 2D numpy de baseball. Llamalo np_baseball.
- Imprime el tipo de np_baseball.
- Imprime el atributo shape de np_baseball. Utiliza np_baseball.shape.


In [ ]:
# Crea baseball, una lista de listas
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Importa el paquete numpy
import numpy as np

# Crea un array 2D numpy de baseball: np_baseball


# Imprime el tipo de np_baseball


# Imprime las dimensiones de np_baseball



<class 'numpy.ndarray'>
(4, 2)


## 8.- Datos de béisbol en 2D
has echado otra mirada a los datos de las Grandes Ligas de Béisbol (MLB) y te das cuenta que tiene más sentido reestructurar toda esa información en un array 2D numpy. Este array debería tener 1015 filas, correspondientes a los 1015 jugadores de béisbol de los cuales tienes información, y dos columnas (para la altura y el peso).

La MLB fue, de nuevo, muy útil y le pasó los datos en una estructura diferente, una lista de listas en Python. En esta lista de listas, cada sublista representa la altura y el peso de un solo jugador de béisbol. El nombre de esta lista embebida es baseball.

¿Puedes almacenar la información como un array 2D para desbloquear las funcionalidades extras de numpy?

### Instrucciones

- Utiliza np.array() para crear un array 2D numpy de la lista baseball. Llamalo np_baseball.
- Imprime el atributo shape de np_baseball.

In [ ]:
# baseball esta disponible como una lista de listas

# Importa el paquete numpy
import numpy as np

# Ejecutar este bloque para que funcione ejemplos posteriores
from data import *

# Crea un array 2D numpy de baseball: np_baseball


# Imprime las dimensiones de np_baseball




(1015, 2)


## 9.- Selección de array 2D con NumPy
Si tu array numpy tiene una estructura regular, por ejemplo, cada fila y columna tiene un valor fijo de valores, formas complicadas de selección se vuelven muy fáciles. Mira el código de abajo, donde los elementos "a" y "c" son extraídos de una lista de listas.

    # Una lista de listas común
    x = [["a", "b"], ["c", "d"]]
    [x[0][0], x[1][0]]

    # numpy
    import numpy as np
    np_x = np.array(x)
    np_x[:,0]
    
Para una lista común de Python, esto es un dolor de cabeza. Para arrays 2D numpy, ¡El tema se vuelve más intuitivo!. Los índices antes de la coma se refieren a las filas mientras que los que le siguen se refieren a las columnas. El : es utilizado para seleccionar; en este ejemplo, le dice a Python que selecciona todas las filas.

El código que convierte la lista precargada baseball en un array 2D numpy ya se encuentra disponible en el guión. La primera columna contiene la altura de los jugadores en pulgadas y la segunda columna contiene el peso de los jugadores en libras. Agrega algunas líneas de código para hacer las respectivas correciones. Recuerda que en Python, ¡El primer elemento está en el índice 0!

### Instrucciones

- Imprime la fila N°50 de np_baseball.
- Crea una nueva variable, np_weight, la cual contiene toda la segunda columna de np_baseball.
- Selecciona la altura (primera columna) del jugador N°124 en np_baseball e imprimelo.


In [ ]:
# baseball está disponible como una lista de listas.

# Importa el paquete numpy
import numpy as np

# Crea np_baseball (2 columnas)
np_baseball = np.array(baseball)

# imprimir la primera fila


# imprimir la última fila



# Imprime la fila N°50 de np_baseball



# Selecciona toda la segunda columna de np_baseball: np_weight


# Imprime la altura del jugador N°124


[ 74 180]
[ 73 195]
[ 70 195]
[180 215 210 ... 205 190 195]
75


## Generación de matrices

In [ ]:
# generación de una matriz con números aleatorios
T = np.random.rand(6, 7)
print(T)

In [ ]:
filas, columnas = T.shape
print(filas)
print(columnas)

In [ ]:
np.random.randint(1, 20, (4, 4))

In [ ]:
np.zeros((2, 4))

In [ ]:
np.ones((1, 4))

In [ ]:
array = np.arange(10)
print(array)

In [ ]:
array = np.arange(10)
print(array)

In [ ]:
np.arange(0,11,3)

In [ ]:
np.linspace(0, 10, 100)

In [ ]:
np.linspace(0, 1, num=10)

In [ ]:
np.logspace(0, 3)


In [ ]:
a = np.arange(1,10).reshape(3, 3)
print(a)

In [ ]:
# También funciona como método
N = a.reshape([3,3])
N = a.reshape(3,3)
N

In [ ]:
# lectura de matriz desde teclado
np_edades = np.array(eval(input('Ingrese la matriz de edades: ')))
print(np_edades)

In [ ]:
eval('2+3+5+6+7')

In [ ]:
filas = int(input('Número de filas: '))
columnas = int(input('Número de columnas: '))

np_edades = np.zeros([filas, columnas])
for f in range(len(np_edades)):
  for c in range(len(np_edades[0])):
    np_edades[f, c] = int(input(f'[{f},{c}]: '))

print(np_edades)

In [ ]:
print(np_table)

In [ ]:
np_table[2, :]

In [ ]:
print(np_table[:, 3])

In [ ]:
np_table[:, -1]

## Referencia

- Bojato, M. (s. f.). Introducción a Python (practice) - DataCamp. Recuperado 8 de julio de 2019, de 2018 website: https://www.datacamp.com/community/open-courses/introduccion-a-python